export const catergory = [
  {
    id: "1",
    title: "Beaches & Costle Areas",
    image: require("./assets/cpic/Beach.jpg"),
    icon: "Waves",
  },
  {
    id: "2",
    title: "Mountains & Scenic Views",
    image: require("./assets/cpic/Mountain.png"),
    icon: "Mountain",
  },
  {
    id: "3",
    title: "Caves & Rock Formations ",
    image: require("./assets/cpic/caves.jpg"),
    icon: "FlameKindling",
  },
  {
    id: "4",
    title: "Waterfalls & Rivers",
    image: require("./assets/cpic/waterfall.jpg"),
    icon: "Droplets",
  },
  {
    id: "5",
    title: "Forests & National Parks  ",
    image: require("./assets/cpic/forest.jpg"),
    icon: "Trees",
  },
  {
    id: "6",
    title: "Islands & Marine Attractions ",
    image: require("./assets/cpic/island.jpg"),
    icon: "TreePalm",
  },
  {
    id: "7",
    title: "Historical & Cultural Sites",
    image: require("./assets/cpic/History.jpg"),
    icon: "Landmark",
  },

  {
    id: "8",
    title: "Religious & Spiritual Places",
    image: require("./assets/cpic/Religious.png"),
    icon: "Church",
  },
  {
    id: "9",
    title: "Adventure & Outdoor Activities",
    image: require("./assets/cpic/outdoor.jpg"),
    icon: "Tent",
  },
  {
    id: "10",
    title: "Urban Attractions",
    image: require("./assets/cpic/urban.jpeg"),
    icon: "Building2",
  },
  {
    id: "11",
    title: "Hot Springs & Natural Pools",
    image: require("./assets/cpic/spring.jpg"),
    icon: "Flame",
  },
  {
    id: "12",
    title: "Cultural Villages & Museums",
    image: require("./assets/cpic/Museum.jpg"),
    icon: "Library",
  },
];

export const districs = [
  {
    name: "Colombo",
    province: "Western Province",
    image: require("./assets/districpics/colombo.jpg"),
  },
  {
    name: "Gampaha",
    province: "Western Province",
    image: require("./assets/districpics/gampaha.jpg"),
  },
  {
    name: "Kalutara",
    province: "Western Province",
    image: require("./assets/districpics/Kalutara.jpg"),
  },
  {
    name: "Kandy",
    province: "Central Province",
    image: require("./assets/districpics/Kandy.jpg"),
  },
  {
    name: "Matale",
    province: "Central Province",
    image: require("./assets/districpics/matale.jpg"),
  },
  {
    name: "Nuwara Eliya",
    province: "Central Province",
    image: require("./assets/districpics/NuwaraEliya.jpg"),
  },
  {
    name: "Galle",
    province: "Southern Province",
    image: require("./assets/districpics/galle.jpg"),
  },
  {
    name: "Matara",
    province: "Southern Province",
    image: require("./assets/districpics/matara.jpg"),
  },
  {
    name: "Hambantota",
    province: "Southern Province",
    image: require("./assets/districpics/hambantota.jpg"),
  },
  {
    name: "Jaffna",
    province: "Northern Province",
    image: require("./assets/districpics/jaffna.jpg"),
  },
  {
    name: "Kilinochchi",
    province: "Northern Province",
    image: require("./assets/districpics/kilinochchi.jpg"),
  },
  {
    name: "Mannar",
    province: "Northern Province",
    image: require("./assets/districpics/mannar.jpg"),
  },
  {
    name: "Mullative",
    province: "Northern Province",
    image: require("./assets/districpics/mullaitivu.jpg"),
  },
  {
    name: "Vavuniya",
    province: "Northern Province",
    image: require("./assets/districpics/vavuniya.jpg"),
  },
  {
    name: "Trincomalee",
    province: "Eastern Province",
    image: require("./assets/districpics/Trincomalee.jpg"),
  },
  {
    name: "Baticaloa",
    province: "Eastern Province",
    image: require("./assets/districpics/baticaloa.jpg"),
  },
  {
    name: "Ampara",
    province: "Eastern Province",
    image: require("./assets/districpics/ampara.jpg"),
  },
  {
    name: "Kurunegala",
    province: "North Western Province",
    image: require("./assets/districpics/kurunegala.jpg"),
  },
  {
    name: "Puttalam",
    province: "North Western Province",
    image: require("./assets/districpics/puttalam.jpg"),
  },
  {
    name: "Anuradapura",
    province: "North Central Province",
    image: require("./assets/districpics/anuradhapura.jpg"),
  },
  {
    name: "Polonnaruwa",
    province: "North Central Province",
    image: require("./assets/districpics/polonnauwa.jpg"),
  },
  {
    name: "Badulla",
    province: "Uva Province",
    image: require("./assets/districpics/badulla.jpg"),
  },
  {
    name: "Monaragala",
    province: "Uva Province",
    image: require("./assets/districpics/monaragala.jpg"),
  },
  {
    name: "Ratnapura",
    province: "Sabaragamuwa Province",
    image: require("./assets/districpics/ratnapura.jpg"),
  },
  {
    name: "Kegalle",
    province: "Sabaragamuwa Province",
    image: require("./assets/districpics/kegalle.jpg"),
  },
];

export const tempTop10 = [
  {
    name: "Galle Dutch Fort",
    description:
      "Galle Fort, a UNESCO World Heritage Site, is a stunning coastal fortress with a rich colonial history. Originally built by the Portuguese in 1588, it was later fortified by the Dutch in the 17th century. Today, it stands as a well-preserved blend of European architecture and South Asian traditions, featuring cobblestone streets, charming boutiques, museums, and breathtaking ocean view",
    geolocation: {
      address: "Galle Fort, Galle, Southern Province, Sri Lanka",
      city: "Galle",
      district: "Galle",
      province: "Southern Province",
      longitude: 80.217,
      latitude: 6.026,
    },
    rating: 4.7,
    category: ["Historical & Cultural Sites", "Urban Attractions"],
    keywords: [
      "UNESCO",
      "Colonial",
      "History",
      "Dutch Fort",
      "Tourist Attraction",
    ],
    image_urls: [
      "https://iainlakewindsvilla.com/wp-content/uploads/2020/07/beach_inns_website_tours_900x500px_galle-3.jpg",
      "https://slrailwayforum.com/content/images/2023/04/Galle-Fort.jpg",
    ],
    contact_info: {
      phone: "+94 91 224 7222",
      website: "https://www.gallefort.lk",
    },
    opening_hours: {
      Monday: "8:00 AM - 6:00 PM",
      Tuesday: "8:00 AM - 6:00 PM",
      Wednesday: "8:00 AM - 6:00 PM",
      Thursday: "8:00 AM - 6:00 PM",
      Friday: "8:00 AM - 6:00 PM",
      Saturday: "8:00 AM - 6:00 PM",
      Sunday: "8:00 AM - 6:00 PM",
    },
    popularity_score: 9.2,
  },
  {
    name: "Sigiriya Rock Fortress",
    description:
      "Sigiriya, an ancient rock fortress and UNESCO World Heritage Site, is one of Sri Lanka’s most iconic landmarks. Rising 200 meters above the surrounding landscape, this majestic site was once a royal palace and later a Buddhist monastery. It is renowned for its well-preserved frescoes of celestial maidens, the polished Mirror Wall covered in centuries-old inscriptions, and the impressive Lion’s Paw entrance. The summit offers breathtaking panoramic views of lush forests and distant mountains, making it a must-visit destination for history enthusiasts and nature lovers alike",
    geolocation: {
      address: "Sigiriya, Central Province, Sri Lanka",
      city: "Sigiriya",
      district: "Matale",
      province: "Central Province",
      longitude: 80.757,
      latitude: 7.957,
    },
    rating: 4.8,
    category: [
      "Historical & Cultural Sites",
      "Hill Country & Scenic Views",
      "Adventure & Outdoor Activities",
    ],
    keywords: ["UNESCO", "Fortress", "Rock", "Ancient City", "Sigiriya"],
    image_urls: [
      "https://beyondescapes.com/uploads/excursions/BW4YPnXzX3u1.jpg",
      "https://d30od4ebpi69u8.cloudfront.net/sites/3/2017/09/sigiriya-lion-paw.jpg",
    ],
    contact_info: {
      phone: "+94 66 228 6005",
      website: "https://www.sigiriyafortress.lk",
    },
    opening_hours: {
      Monday: "7:00 AM - 5:30 PM",
      Tuesday: "7:00 AM - 5:30 PM",
      Wednesday: "7:00 AM - 5:30 PM",
      Thursday: "7:00 AM - 5:30 PM",
      Friday: "7:00 AM - 5:30 PM",
      Saturday: "7:00 AM - 5:30 PM",
      Sunday: "7:00 AM - 5:30 PM",
    },
    popularity_score: 9.6,
  },
  {
    name: "Temple of the Tooth Relic",
    description:
      "The Temple of the Sacred Tooth Relic, located in the heart of Kandy, is one of the most revered Buddhist sites in Sri Lanka and a UNESCO World Heritage Site. This sacred temple houses the relic of the Buddha’s tooth, which is believed to bring divine protection to the island. Set within the historic Royal Palace complex, the temple features intricate Kandyan architecture, golden-roofed shrines, and beautifully adorned halls. Pilgrims and visitors gather daily to witness the rituals and pay homage, while the annual Esala Perahera festival showcases a grand procession with traditional dancers, drummers, and beautifully decorated elephants in honor of the sacred relic",
    geolocation: {
      address: "Sri Dalada Veediya, Kandy, Central Province, Sri Lanka",
      city: "Kandy",
      district: "Kandy",
      province: "Central Province",
      longitude: 80.635,
      latitude: 7.2936,
    },
    rating: 4.7,
    category: ["Religious & Spiritual Places", "Historical & Cultural Sites"],
    keywords: ["Buddhism", "Temple", "Tooth Relic", "UNESCO", "Kandy"],
    image_urls: [
      "https://cdn.britannica.com/19/118219-050-8BA0B67E/Dalada-Maligava-tooth-Buddha-Sri-Lanka-Kandy.jpg",
      "https://amayaresorts.imgix.net/sites/2/2022/11/Untitled-design-16.png?w=510&h=530&&fit=crop&crop=center&auto=format&q=25https://mahaweli.lk/wp-content/uploads/2023/06/Temple-Tooth-Relic.jpg",
    ],
    contact_info: {
      phone: "+94 81 223 4226",
      website: "https://www.sridaladamaligawa.lk",
    },
    opening_hours: {
      Monday: "5:30 AM - 8:00 PM",
      Tuesday: "5:30 AM - 8:00 PM",
      Wednesday: "5:30 AM - 8:00 PM",
      Thursday: "5:30 AM - 8:00 PM",
      Friday: "5:30 AM - 8:00 PM",
      Saturday: "5:30 AM - 8:00 PM",
      Sunday: "5:30 AM - 8:00 PM",
    },
    popularity_score: 9.4,
  },
  {
    name: "Yala National Park",
    description:
      "Yala National Park, Sri Lanka’s most famous wildlife sanctuary, is renowned for its high density of leopards, making it one of the best places in the world to spot these elusive big cats. Spanning diverse landscapes of dry forests, grasslands, and coastal lagoons, the park is also home to large herds of elephants, sloth bears, crocodiles, and over 200 bird species. Its breathtaking scenery, combined with the thrill of wildlife safaris, makes Yala a must-visit destination for nature lovers and adventure seekers",
    geolocation: {
      address: "Yala, Southern Province, Sri Lanka",
      city: "Tissamaharama",
      district: "Hambantota",
      province: "Southern Province",
      longitude: 81.4667,
      latitude: 6.3667,
    },
    rating: 4.6,
    category: ["Nature & Wildlife", "Adventure & Outdoor Activities"],
    keywords: ["Wildlife", "Leopards", "Safari", "Elephants", "Birdwatching"],
    image_urls: [
      "https://images.squarespace-cdn.com/content/v1/5a3bb03b4c326d76de73ddaa/a2345362-8172-4329-9fc7-010cf2a19b25/The+Common+Wanderer-8796-2.jpg",
      "https://www.srilankalocaltours.com/wp-content/uploads/safari-trip-to-Yala-National-Park-1.jpg",
      "https://travellersisle.com/wp-content/uploads/2022/08/Crowded-Yala-national-park.jpg",
      "https://www.yalanationalpark.lk/images/yala-national-park-leopard-1.jpg",
      "https://i.pinimg.com/originals/a5/93/29/a593298c8c454e95126868512140a12e.jpg",
      "https://www.yalapark.com/images/yalapark-elephant.jpg",
      "https://www.yalapark.com/images/yala-national-park-wild-boar.jpg",
      "https://www.yalapark.com/images/yala-national-park-birds.jpg",
      "https://www.yalapark.com/images/yala-national-park-landscape.jpg",
      "https://www.yalapark.com/images/yala-national-park-buffalo.jpg",
      "https://www.yalapark.com/images/yala-national-park-deer.jpg",
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/8e/3c/1d/yala-national-park.jpg?w=1200&h=-1&s=1",
      "https://www.yala-national-park.com/images/yala-leopard-sri-lanka.jpg",
      "https://www.srilankainstyle.com/wp-content/uploads/2021/05/yala-national-park-jeep-safari-sri-lanka.jpg",
      "https://i.natgeofe.com/n/7b7f583e-9086-4f90-8e6f-719325988d8b/yala-national-park-leopard_2x3.jpg",
    ],
    contact_info: {
      phone: "+94 47 223 5002",
      website: "https://www.yalasafari.lk",
    },
    opening_hours: {
      Monday: "6:00 AM - 6:00 PM",
      Tuesday: "6:00 AM - 6:00 PM",
      Wednesday: "6:00 AM - 6:00 PM",
      Thursday: "6:00 AM - 6:00 PM",
      Friday: "6:00 AM - 6:00 PM",
      Saturday: "6:00 AM - 6:00 PM",
      Sunday: "6:00 AM - 6:00 PM",
    },
    popularity_score: 9.1,
  },
  {
    name: "Ella Rock",
    description:
      "Ella Rock is a popular hiking destination that offers breathtaking panoramic views of lush green mountains, deep valleys, and tea plantations. The challenging yet rewarding trek takes visitors through misty forests, scenic trails, and railway tracks, providing an unforgettable experience for adventure enthusiasts. At the summit, hikers are rewarded with stunning sunrise or sunset views, making Ella Rock a must-visit spot for nature lovers and photographers",
    geolocation: {
      address: "Ella, Uva Province, Sri Lanka",
      city: "Ella",
      district: "Badulla",
      province: "Uva Province",
      longitude: 81.0466,
      latitude: 6.8667,
    },
    rating: 4.8,
    category: ["Hill Country & Scenic Views", "Adventure & Outdoor Activities"],
    keywords: ["Hiking", "Scenic Views", "Nature", "Ella", "Mountains"],
    image_urls: [
      "https://images.squarespace-cdn.com/content/v1/5c32d3a189c172393734742d/1557887127824-T12Q01U2ILE5IBD9RHRU/ELLA+ROCK.jpg",
      "https://www.visitella.com/img/gallery/gallery_main/22/1.png",
    ],
    contact_info: {
      phone: "N/A",
      website: "N/A",
    },
    opening_hours: {
      Monday: "Open 24 hours",
      Tuesday: "Open 24 hours",
      Wednesday: "Open 24 hours",
      Thursday: "Open 24 hours",
      Friday: "Open 24 hours",
      Saturday: "Open 24 hours",
      Sunday: "Open 24 hours",
    },
    popularity_score: 9.3,
  },
  {
    name: "Mirissa Beach",
    description:
      "Mirissa is a breathtaking coastal paradise known for its golden sandy beaches, swaying palm trees, and vibrant atmosphere. This idyllic destination is one of the best places in Sri Lanka for whale watching, offering the chance to spot blue whales, dolphins, and other marine life. Beyond its natural beauty, Mirissa boasts a lively nightlife scene with beachfront bars, fresh seafood restaurants, and music-filled evenings. Whether you're looking to relax by the shore, embark on an ocean adventure, or enjoy the energetic beach vibes, Mirissa offers a perfect tropical escape",
    geolocation: {
      address: "Mirissa, Southern Province, Sri Lanka",
      city: "Mirissa",
      district: "Matara",
      province: "Southern Province",
      longitude: 80.4521,
      latitude: 5.9486,
    },
    rating: 4.7,
    category: ["Beaches & Costle Areas", "Adventure & Outdoor Activities"],
    keywords: ["Beach", "Surfing", "Whale Watching", "Sunset", "Mirissa"],
    image_urls: [
      "https://digitaltravelcouple.com/wp-content/uploads/2020/01/mirissa-beach-sri-lanka-1.jpg",
      "https://www.theglobetrottergp.com/wp-content/uploads/2019/05/Secret-beach-in-mirissa-sri-lanka.jpg",
    ],
    contact_info: {
      phone: "N/A",
      website: "N/A",
    },
    opening_hours: {
      Monday: "Open 24 hours",
      Tuesday: "Open 24 hours",
      Wednesday: "Open 24 hours",
      Thursday: "Open 24 hours",
      Friday: "Open 24 hours",
      Saturday: "Open 24 hours",
      Sunday: "Open 24 hours",
    },
    popularity_score: 9.5,
  },
];

export const topHotels = [
  {
    id: "h1",
    name: "Cinnamon Grand Colombo",
    location: "Colombo, Western Province",
    price: 35000,
    rating: 4.8,
    image: "https://www.cvent.com/venues/_next/image?url=https%3A%2F%2Fimages.cvent.com%2Fcsn%2Fbe1da351-c8fb-4ff4-b26d-1afa3bac6e17%2Fimages%2F55e2456e89cc413aa2ba16cca3123bb3_large!_!93422dbcfd6ff08924b489746fc72ead.jpg&w=3840&q=80",
    tags: ["Luxury", "City Hotel", "Spa"],
    amenities: ["wifi", "pool", "silverware-fork-knife", "spa"],
  },
  {
    id: "h2",
    name: "Heritance Kandalama",
    location: "Dambulla, Central Province",
    price: 45000,
    rating: 4.9,
    image: "https://exploresrilanka.lk/wp-content/uploads/2013/11/1-copy2-1.webp",
    tags: ["Eco-friendly", "Nature", "Luxury"],
    amenities: ["wifi", "pool", "leaf", "spa"],
  },
  {
    id: "h3",
    name: "Shangri-La Hambantota",
    location: "Ambalantota, Southern Province",
    price: 52000,
    rating: 4.7,
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/8f/bc/d4/shangri-la-hambantota.jpg?w=900&h=500&s=1",
    tags: ["Resort", "Golf", "Beachfront"],
    amenities: ["wifi", "pool", "golf", "beach"],
  },
  {
    id: "h4",
    name: "98 Acres Resort & Spa",
    location: "Ella, Uva Province",
    price: 42000,
    rating: 4.9,
    image: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/123777522.jpg?k=d68c52c58bdec8f871e51d89c80a0ac988559b40f89423842a52ea096e967d37&o=",
    tags: ["Boutique", "Views", "Honey Moon"],
    amenities: ["wifi", "pool", "terrain", "spa"],
  },
  {
    id: "h5",
    name: "Araliya Green Hills",
    location: "Nuwara Eliya, Central Province",
    price: 28000,
    rating: 4.5,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyWPOhcTOZqncB4EyTi54JyJDvAgL6nL2HzA&s",
    tags: ["Hill Country", "Cozy", "Family"],
    amenities: ["wifi", "pool", "fire", "silverware-fork-knife"],
  },
];
